sudo: required

services:
 - docker

before_install:
 - docker build -t kunalchoudhary2/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true kunalchoudhary2/react-test npm test -- --coverage

after_success:
 - docker build -t kunalchoudhary2/multi-client ./client
 - docker build -t kunalchoudhary2/multi-nginx ./nginx
 - docker build -t kunalchoudhary2/multi-server ./server
 - docker build -t kunalchoudhary2/multi-worker ./worker

#log in to the docker cli. Updated credentials in travis
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take these images and push them to docker hub
 - docker push kunalchoudhary2/multi-client
 - docker push kunalchoudhary2/multi-nginx
 - docker push kunalchoudhary2/multi-server
 - docker push kunalchoudhary2/multi-worker
